### ISSUE TITLE
How to use from ClojureScript?

### ISSUE THREAD

**Issue by theronic** [leonoel/clope#1]
`(c/wrap "something")` returns nil in Cljs. How do I use clope?

**Comment by leonoel** [comment]
clope operates at the byte level, it is agnostic of characters and encoding. `wrap` expects a raw byte chunk (byte array on the JVM, ArrayBuffer on javascript). If you want to model character strings with ropes, you first need to implement the encoding logic to turn strings into bytes and vice-versa.

**Comment by theronic** [comment]
Solution:
```
(let [encoder (js/TextEncoder.)]
  (c/wrap (.encode encoder "hello world!")))
```
